default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: postgres
  pool: 5

development:
  <<: *default
  database: text-to-image_sharing_development


test:
  <<: *default
  database: text-to-image_sharing_test